name: Seminar
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - notebook
  - matplotlib
  - jupyterlab
  - ipympl
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - numpy
  - pandas